#!/usr/bin/env python3

import sys
from functools import reduce
import re

subs = {
        "Name=":"",
        "gene":"CDS",
        "cox1":"gene=COX1; product=cytochrome c oxidase subunit I",
        "cox2":"gene=COX2; product=cytochrome c oxidase subunit II",
        "atp8":"gene=ATP8; product=ATP synthase F0 subunit 8",
        "atp6":"gene=ATP6; product=ATP synthase F0 subunit 6",
        "cox3":"gene=COX3; product=cytochrome c oxidase subunit III",
        "nad3":"gene=ND3; product=NADH dehydrogenase subunit 3",
        "nad5":"gene=ND5; product=NADH dehydrogenase subunit 5",
        "nad4l":"gene=ND4L; product=NADH dehydrogenase subunit 4L",
        "nad4":"gene=ND4; product=NADH dehydrogenase subunit 4",
        "nad6":"gene=ND6; product=NADH dehydrogenase subunit 6",
        "cob":"gene=CYTB; product=cytochrome b",
        "nad1":"gene=ND1; product=NADH dehydrogenase subunit 1",
        "nad2":"gene=ND2; product=NADH dehydrogenase subunit 2",
        "trnL2(tta)":"gene=trnL2-uaa; product=tRNA-Leu; note=anticodon:uaa",
        "trnK(aaa)":"gene=trnK-uuu; product=tRNA-Lys; note=anticodon:uuu",
        "trnK(aag)":"gene=trnK-cuu; product=tRNA-Lys; note=anticodon:cuu",
        "trnD(gac)":"gene=trnD-guc; product=tRNA-Asp; note=anticodon:guc",
        "trnG(gga)":"gene=trnG-ucc; product=tRNA-Gly; note=anticodon:ucc",
        "trnA(gca)":"gene=trnA-ugc; product=tRNA-Ala; note=anticodon:ugc",
        "trnR(cga)":"gene=trnR-ucg; product=tRNA-Arg; note=anticodon:ucg",
        "trnN(aac)":"gene=trnN-guu; product=tRNA-Asn; note=anticodon:guu",
        "trnS1(aga)":"gene=trnS1-ucu; product=tRNA-Ser; note=anticodon:ucu",
        "trnS1(agt)":"gene=trnS1-acu; product=tRNA-Ser; note=anticodon:acu",
        "trnS1(agc)":"gene=trnS1-gcu; product=tRNA-Ser; note=anticodon:gcu",
        "trnE(gaa)":"gene=trnE-uuc; product=tRNA-Glu; note=anticodon:uuc",
        "trnF(ttc)":"gene=trnF-gaa; product=tRNA-Phe; note=anticodon:gaa",
        "trnH(cac)":"gene=trnH-gug; product=tRNA-His; note=anticodon:gug",
        "trnT(aca)":"gene=trnT-ugu; product=tRNA-Thr; note=anticodon:ugu",
        "trnP(cca)":"gene=trnP-ugg; product=tRNA-Pro; note=anticodon:ugg",
        "trnS2(tca)":"gene=trnS2-uga; product=tRNA-Ser; note=anticodon:uga",
        "trnL1(cta)":"gene=trnL1-uag; product=tRNA-Leu; note=anticodon:uag",
        "trnV(gta)":"gene=trnV-uac; product=tRNA-Val; note=anticodon:uac",
        "trnM(atg)":"gene=trnM-cau; product=tRNA-Met; note=anticodon:cau",
        "trnI(atc)":"gene=trnI-gau; product=tRNA-Ile; note=anticodon:gau",
        "trnQ(caa)":"gene=trnQ-uug; product=tRNA-Gln; note=anticodon:uug",
        "trnW(tga)":"gene=trnW-uca; product=tRNA-Trp; note=anticodon:uca",
        "trnC(tgc)":"gene=trnC-gca; product=tRNA-Cys; note=anticodon:gca",
        "trnY(tac)":"gene=trnY-uac; product=tRNA-Tyr; note=anticodon:gua",
        "rrnL":"gene=rrnL; product=large subunit ribosomal RNA",
        "rrnS":"gene=rrnS; product=small subunit ribosomal RNA"
        }
        
if len(sys.argv) > 1:
    filename = sys.argv[1]
    with open(filename) as gff:
        for line in gff:
            line = line.split()
            last_collumn = re.sub("-[0-9]$", "",line[8]) #Removes "-0" and "-1" from duplicated features
            last_collumn = reduce(lambda a, kv: a.replace(*kv), subs.items(), last_collumn) #Formats last collumn substituting key/values pairs
            print(line[0],
                    line[1],
                    line[2].replace("gene","CDS"),
                    line[3],
                    line[4],
                    line[5],
                    line[6],
                    line[7],
                    last_collumn, sep= "\t")
else:
    print("This script converts .gff files generated by MitosWebServer to a modified .gff that can be exported to the Artemis Annotation tool\nUsage: python3 mitos_to_artemis.py filename.gff")
